# Site settings
name: 刘鼎豪
location: 浙江
company: Google
position: 划水大师，白嫖领袖
github: https://github.com/ringldh
phone: 13222488692
email: 1837169149@qq.com  ringldh@gmail.com

baseurl: "/resume.io"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown


theme: jekyll-theme-cayman
